### ISSUE TITLE
pubtools-pulp-clear-repo: Allow --content-type to be specified multiple times

### ISSUE THREAD

**Issue by rbikar** [release-engineering/pubtools-pulp#25]
#### Summary

Currently pubtools-pulp-clear-repo accepts --content-type arg. only as comma separated list. I would like propose an improvement for that behavior. Let's make pubtools-pulp-clear-repo accept --content-type multiple times as well. This might be more convenient for machine-like callers and also it would follow  "Be liberal what you accept" design principle.

#### Issue Type
- Feature Request

#### Current behavior

pubtools-pulp-clear-repo  will not work correctly when run as:
`pubtools-pulp-clear-repo --content-type a --content-type b`
The ArgParser will take only the last value into account (most likely)

#### Desired behavior

`pubtools-pulp-clear-repo --content-type a --content-type b` will clear repo for content  type a and b.
**But the original behavior should be preserved.**
So pubtools-pulp-clear-repo can handle --content-type as comma separated list and also can be specified multiple times.

#### Use case

`pubtools-pulp-clear-repo --content-type a --content-type b` - clears repo for content  type a and b.

#### Additional Information

No additional information.

**Comment by AvlWx2014** [comment]
There is some overlap here with my work on another task, so I decided to take a look. It is possible to support:
* Multiple instances of `--content-type` (desired behavior outlined in this issue)
* One instance of `--content-type` appearing as a comma-delimited list (current behavior)
* One instance of `--content-type` appearing as a space-delimited list (new behavior). I think this new behavior would be consistent with other command-line interfaces that allow multiple values for one option. Example: `--content-type rpm contentType1 contentType2`. The biggest drawback I can think of for this is that it imposes an ordering that may or may not already exist e.g. `pulp clear-repo <reponame> --content-type rpm contentType1 contentType2` works, while `pulp clear-repo --content-type rpm contentType1 contentType2 <reponame>` does not. In the latter case, `<reponame>` will be consumed as a value for the `--content-type` option.

**Comment by rbikar** [comment]
@AvlWx2014 
I think the very similar thing was already done for another command - can you check https://github.com/release-engineering/pubtools-pulp/pull/31/ , if it can be re-used?  Btw I can't find where "space-delimited list" behavior is required.

**Comment by AvlWx2014** [comment]
The approach I had in mind uses a subclass of [argparse.Action](https://docs.python.org/3/library/argparse.html#argparse.Action), which should work at least as far back as 2.7. I'd have to test if it's available on 2.6, but if not then the combination of a `action="append"` and a function to sanitize the content-type list as is done in #31 would work as well.

The space-delimited list behavior is not required - just a brainstorm I had while reading this issue.

**Comment by rohanpm** [comment]
For these projects, there is a documented convention we want to follow, at https://release-engineering.github.io/pubtools/devguide.html#argument-conventions .

**Comment by AvlWx2014** [comment]
This is handy, thank you for sharing. I will forgo the space separated list idea
